### ISSUE TITLE
Lambda error when using Add columns operation

### ISSUE THREAD

**Issue by lucasmsp** [eubr-bigsea/juicer#224]
When using add columns operations (in Spark platform) to join two equals datasets, the execution crashes due by TypeError: <lambda>() missing 1 required positional argument: 'inx' 

Traceback (most recent call last):
  File "/tmp/juicer_app_4_4_41.py", line 713, in main
    task_futures['e39d7f68-75e4-491b-9819-4ce248152430'].result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/juicer_app_4_4_41.py", line 707, in <lambda>
    lambda: add_columns_8(spark_session, cached_state, emit_event))
  File "/tmp/juicer_app_4_4_41.py", line 567, in add_columns_8
    input1_indexed = _add_column_index(out5, 'ds0_')
  File "/tmp/juicer_app_4_4_41.py", line 565, in _add_column_index
    lambda row, inx: row + (inx,)).toDF(new_attrs)
  File "/usr/local/spark/python/pyspark/sql/session.py", line 58, in toDF
    return sparkSession.createDataFrame(self, schema, sampleRatio)
  File "/usr/local/spark/python/pyspark/sql/session.py", line 746, in createDataFrame
    rdd, schema = self._createFromRDD(data.map(prepare), schema, samplingRatio)
  File "/usr/local/spark/python/pyspark/sql/session.py", line 390, in _createFromRDD
    struct = self._inferSchema(rdd, samplingRatio, names=schema)
  File "/usr/local/spark/python/pyspark/sql/session.py", line 361, in _inferSchema
    first = rdd.first()
  File "/usr/local/spark/python/pyspark/rdd.py", line 1378, in first
    rs = self.take(1)
  File "/usr/local/spark/python/pyspark/rdd.py", line 1360, in take
    res = self.context.runJob(self, takeUpToNumLeft, p)
  File "/usr/local/spark/python/pyspark/context.py", line 1069, in runJob
    sock_info = self._jvm.PythonRDD.runJob(self._jsc.sc(), mappedRDD._jrdd, partitions)
...
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 377, in
 main process()
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 372, in  process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 39
3, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/usr/local/spark/python/pyspark/rdd.py", line 1354, in takeUpToNumLeft
    yield next(iterator)
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/util.py", line 99, in wrapper
    return f(*args, **kwargs)
TypeError: <lambda>() missing 1 required positional argument: 'inx

**Comment by waltersf** [comment]
Fixed
