### ISSUE TITLE
get_X_train_data incompatible with Quantile discretizer when len(features)==1

### ISSUE THREAD

**Issue by victorgveloso** [eubr-bigsea/juicer#307]
https://github.com/eubr-bigsea/juicer/blob/6adbfe25e5c721483587b246afff3f8cbb7822b2/juicer/scikit_learn/util.py#L4
Quantile discretizer generated code:
![Screenshot_20210113_062129](https://user-images.githubusercontent.com/11022419/104433261-a8176f80-5568-11eb-81fc-9abfa1ec6485.png)
branching at method: get_X_train_data; file: util.py; line: 24
https://github.com/eubr-bigsea/juicer/blob/6adbfe25e5c721483587b246afff3f8cbb7822b2/juicer/scikit_learn/util.py#L24
converts output to Series, but `model2.fit_transform(X_train)` parameter should be dataframe (2D array)

get_X_train_data generated code commented:
![Screenshot_20210113_062112](https://user-images.githubusercontent.com/11022419/104433267-a9489c80-5568-11eb-97c7-03716c847e87.png)

Should that line be removed from get_X_train_data?

**Comment by victorgveloso** [comment]
Raised exception:
```
Traceback (most recent call last):
  File "/tmp/mozilla_victorguerraveloso0/workflow_69.py", line 167, in <module>
    main()
  File "/tmp/mozilla_victorguerraveloso0/workflow_69.py", line 160, in main
    output_data_2['stars'] = model2.fit_transform(X_train).flatten().tolist()
  File "/tmp/mozilla_victorguerraveloso0/venv/lib/python3.9/site-packages/sklearn/base.py", line 699, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/tmp/mozilla_victorguerraveloso0/venv/lib/python3.9/site-packages/sklearn/preprocessing/_discretization.py", line 153, in fit
    X = self._validate_data(X, dtype='numeric')
  File "/tmp/mozilla_victorguerraveloso0/venv/lib/python3.9/site-packages/sklearn/base.py", line 421, in _validate_data
    X = check_array(X, **check_params)
  File "/tmp/mozilla_victorguerraveloso0/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/tmp/mozilla_victorguerraveloso0/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 637, in check_array
    raise ValueError(
ValueError: Expected 2D array, got 1D array instead:
array=[87 87 87 ... 90 90 90].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
```
Exception on citrus:
![Screenshot_20210113_063939](https://user-images.githubusercontent.com/11022419/104434718-4c4de600-556a-11eb-86a4-e4e1a251a285.png)

**Comment by lucasmsp** [comment]
Hi @victorgveloso, please check if this error continues.

**Comment by victorgveloso** [comment]
It worked!
